### ISSUE TITLE
Error when installing ace

### ISSUE THREAD

**Issue by tanoury1** [duartegroup/mlp-train#71]
Hi, I wanted to update my version of mlp-train, so I cloned the latest version into a new directory. 
When I ran ./install_ace.sh, I got the following error:
Downloading and Extracting Packages

Preparing transaction: done
Verifying transaction: done
Executing transaction: done
Installing pip dependencies: \ Ran pip subprocess with arguments:
['/cluster/home/tanoury/miniconda3/envs/mlptrain-gap/bin/python', '-m', 'pip', 'install', '-U', '-r', '/cluster/home/tanoury/Duarte-codes/mlp-train/condaenv.qe6v9f11.requirements.txt', '--exists-action=b']
Pip subprocess output:
Collecting ase@ git+https://gitlab.com/ase/ase@f2615a6e9a (from -r /cluster/home/tanoury/Duarte-codes/mlp-train/condaenv.qe6v9f11.requirements.txt (line 2))
  Cloning https://gitlab.com/ase/ase (to revision f2615a6e9a) to /tmp/pip-install-37y1t8ln/ase_469e2cf96b3f4202a10b4aae64cbaae6

Pip subprocess error:
  Running command git clone --quiet https://gitlab.com/ase/ase /tmp/pip-install-37y1t8ln/ase_469e2cf96b3f4202a10b4aae64cbaae6
  error: RPC failed; result=22, HTTP code = 422
  fatal: The remote end hung up unexpectedly
  error: subprocess-exited-with-error
  
  × git clone --quiet https://gitlab.com/ase/ase /tmp/pip-install-37y1t8ln/ase_469e2cf96b3f4202a10b4aae64cbaae6 did not run successfully.
  │ exit code: 128
  ╰─> See above for output.
  
  note: This error originates from a subprocess, and is likely not a problem with pip.
error: subprocess-exited-with-error

× git clone --quiet https://gitlab.com/ase/ase /tmp/pip-install-37y1t8ln/ase_469e2cf96b3f4202a10b4aae64cbaae6 did not run successfully.
│ exit code: 128
╰─> See above for output.

note: This error originates from a subprocess, and is likely not a problem with pip.

failed

CondaEnvException: Pip failed

Thank you for the help,
Jerry

**Comment by danielhollas** [comment]
Thanks for the report! It looks like this is a strange Gitlab issue described here:
https://stackoverflow.com/questions/32533379/git-error-rpc-failed-result-22-http-code-404

Could you please modify the `environment_ace.yml` file? On the last line, replace
```
    - ase@git+https://gitlab.com/ase/ase@f2615a6e9a # For PLUMED
```
with
```
    - ase@git+https://gitlab.com/ase/ase.git@f2615a6e9a # For PLUMED
```

(in other words, add `.git` before `@` in the URL). If this resolves the problem for you we'll fix it on the main branch.

**Comment by danielhollas** [comment]
Out of interest, can you post the output of `git --version`? It looks like Gitlab does not play nicely with old git versions.

**Comment by tanoury1** [comment]
Hi Daniel, it was my git version. The cluster I’m working on has version
1.8.x as default. Updated to 2.1.x and no errors.

Thanks, Jerry
