### ISSUE TITLE
Questions about DA_paper: PBC

### ISSUE THREAD

**Issue by physorgchem** [duartegroup/mlp-train#83]
@Hanwen1018 I am attempting to go through your DA_paper examples. I am curious about which branch I should use – main or Hanwen/PBC-AL. Have I understood correctly that in the DA_paper examples, both training and later mlp-MD were conducted with a cluster model (non-PBC)? Thanks!

**Comment by juraskov** [comment]
Hi, the PBC-AL branch was added recently and contains an experimental implementation of PBC sampling in the AL. Please continue to use the main branch. To clarify the paper, the training and the AL were performed using a cluster model (i.e., non-PBC as you mentioned), but the MD simulations with the final version of the potential were done in PBC. We observed that the MLPs trained with cluster data are well transferable to the PBC and provide stable and reliable dynamics.

Veronika
